package com.st10345224.socialmediaapp

data class Post(
    val userId: String, // Add userId
    val username: String,
    val timestamp: Long, // Changed to Long for easier sorting
    val content: String,
    val imageString: String? = null, // Store Base64 string, null if no image
    var likes: Int = 0, // Initialize to 0
    var comments: Int = 0, // Initialize to 0
    var shares: Int = 0, // Initialize to 0
    val postId: String? = null // Add postId, nullable since it's generated by Firestore
)